version: '3.8'

services:
  worker:
    build:
      context: ./worker2
    ports:
      - "80:8080"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - PORT=8080
      - WORKER_SECRET=super_secret_token
      - MOCK_MEDIA_PROVIDER=false
    restart: unless-stopped
